=== COMP4711-Lab07/dtd/data/schedule.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- A schedule defines the day, time, course, instructor, and room  -->
<!ELEMENT schedule (day+, time+, courseno, instructor+, room+)>
<!ELEMENT dayofweek (time, courseno, room, instructor)>
<!ELEMENT course (room, instructor, time, day)>
<!ELEMENT classperiod (day, courseno, room, instructor)>

<!--A day determines the day of the week -->
<!ELEMENT day (#PCDATA)>
<!ATTLIST day
    type    (m|t|w|t|f|s|su) "m"
>

<!-- Time is flexible and can be set as any time of day -->
<!ELEMENT time (#PCDATA)>

<!-- CourseNo is predetermined and unique for all courses -->
<!ELEMENT courseno (#PCDATA)>
<!ATTLIST courseno
    type    (lecture|lab) "lecture"
>

<!-- Instructors teaching courses. Can be same or different for various classes -->
<!ELEMENT instructor (#PCDATA)>

<!-- Room where the lecture takes place. Defined as building-roomNo -->
<!ELEMENT room (#PCDATA)>

=== COMP4711-Lab07/dtd/data/course.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE course SYSTEM 'schedule.dtd'>
<course type="lab" id="comp4932">
    <info>
        <day type="mon">Monday</day>
        <time block="830">830</time>
        <courseno>COMP4932</courseno>
        <instructor>Dennis Richards</instructor>
        <room>se12-308</room> 
    </info>
</course>


<course type="lec" id="comp4735">
    <info>
        <day type="mon">Monday</day>
        <time block="830">830</time>
        <courseno>COMP4932</courseno>
        <instructor>Mirela Gutica</instructor>
        <room>se12-308</room> 
    </info>
</course>
